[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Tokyonight-Dark-Borderless
Comment=An elegant GTK theme with the 'Tokyonight Dark' colour palette, and based on '@Vinceliuice's Graphite' GTK theme.
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Tokyonight-Dark-Borderless
MetacityTheme=Tokyonight-Dark-Borderles
IconTheme=Tokyonight-Dark
CursorTheme=Tokyonight-Dark
ButtonLayout=close,minimize,maximize:menu

