[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Tokyonight_Light-Borderless
Comment=An elegant GTK theme with the 'Tokyonight Light' colour palette, and based on '@Vinceliuice's Graphite' GTK theme.
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Tokyonight_Light-Borderless
MetacityTheme=Tokyonight_Light-Borderless
IconTheme=Tokyonight_Light
CursorTheme=Tokyonight_Light
ButtonLayout=close,minimize,maximize:menu
